# Generated by Django 4.0.1 on 2022-10-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vega', '0003_historyobject'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_language', models.CharField(max_length=100)),
                ('from_language', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('translate', models.CharField(max_length=1000)),
            ],
        ),
    ]
